name: Android CI

on:
  push:
    branches-ignore: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.SECRET_SQUIRREL }}
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run unit tests
      run: |
        echo "$SUPER_SECRET" > test.txt
        bash ./gradlew test --info --stacktrace
